#!/bin/bash
VERSION=$(sed -n 's/VERSION="\(.*\)"/\1/p' .env)

if [[ -n "$VERSION" ]]; then
  IFS='.' read -r -a ADDR <<< "$VERSION"
  last_index=$((${#ADDR[@]} - 1))
  ADDR[last_index]=$((${ADDR[last_index]} + 1))
  NEW_VERSION=$(IFS=.; echo "${ADDR[*]}")

  perl -pi -e "s/$VERSION/$NEW_VERSION/g" .env
  echo "New version: $NEW_VERSION"
  git add .env
fi